# Setup
title:        Descargas
tagline:      Repositorio oficial y actualizado de descargas de Bucle RO
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Bucle RO
  url:        https://bucle-foro.ml 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
